### ISSUE TITLE
function hasCharacterRelative() should take a signed offset

### ISSUE THREAD

**Issue by simonward** [chockenberry/MarkdownAttributedString#6]
The function:
`static BOOL hasCharacterRelative(NSString *string, NSRange range, NSUInteger offset, unichar character)`
takes a NSUInteger offset. Many clients of this call pass -1.

**Comment by chockenberry** [comment]
Good catch! Fixed with https://github.com/chockenberry/MarkdownAttributedString/commit/54e6774c2436b72e0ac2c8b2c72117233a1e649d
